------------------------------------ DICTIONARY_ ----------------------------------------
-- 时段
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD', '时段', '时段', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD_1', '空腹', '空腹', 'TIME_PERIOD', '1', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD_2', '早餐后2h', '早餐后2h', 'TIME_PERIOD', '2', 0, 2, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD_3', '中餐前', '中餐前', 'TIME_PERIOD', '3', 0, 3, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD_4', '中餐后2h', '中餐后2h', 'TIME_PERIOD', '4', 0, 4, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD_5', '晚餐前', '晚餐前', 'TIME_PERIOD', '5', 0, 5, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD_6', '晚餐后2h', '晚餐后2h', 'TIME_PERIOD', '6', 0, 6, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD_7', '22:00', '22:00', 'TIME_PERIOD', '7', 0, 7, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('TIME_PERIOD_8', '3:00', '3:00', 'TIME_PERIOD', '8', 0, 8, NULL);

-- 意识①②③④⑤⑥⑦⑧⑨⑩
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS', '意识', '意识', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS_1', '清楚', '清楚', 'CONSCIOUSNESS', '①', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS_2', '嗜睡', '嗜睡', 'CONSCIOUSNESS', '②', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS_3', '昏睡', '昏睡', 'CONSCIOUSNESS', '③', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS_4', '朦胧', '朦胧', 'CONSCIOUSNESS', '④', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS_5', '浅昏迷', '浅昏迷', 'CONSCIOUSNESS', '⑤', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS_6', '中昏迷', '中昏迷', 'CONSCIOUSNESS', '⑥', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS_7', '深昏迷', '深昏迷', 'CONSCIOUSNESS', '⑦', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CONSCIOUSNESS_8', '模糊', '模糊', 'CONSCIOUSNESS', '⑧', 0, 0, NULL);

-- 瞳孔对光反应↑↓0
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PUPIL_LIGHT', '瞳孔对光反应', '瞳孔对光反应', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PUPIL_LIGHT_1', '灵敏', '灵敏', 'PUPIL_LIGHT', '↑', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PUPIL_LIGHT_2', '迟钝', '迟钝', 'PUPIL_LIGHT', '↓', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PUPIL_LIGHT_3', '消失', '消失', 'PUPIL_LIGHT', '0', 0, 0, NULL);

-- 给氧方式①②③④
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OXYGEN_WAY', '给氧方式', '给氧方式', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OXYGEN_WAY_1', '鼻氧管', '鼻氧管', 'OXYGEN_WAY', '①', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OXYGEN_WAY_2', '面罩', '面罩', 'OXYGEN_WAY', '②', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OXYGEN_WAY_3', '无创', '无创', 'OXYGEN_WAY', '③', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OXYGEN_WAY_4', '有创', '有创', 'OXYGEN_WAY', '④', 0, 0, NULL);

-- 痰液性状
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('QUALE', '痰液性状', '痰液性状', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('QUALE_1', '白粘痰', '白粘痰', 'QUALE', '①', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('QUALE_2', '黄脓痰', '黄脓痰', 'QUALE', '②', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('QUALE_3', '血性痰', '血性痰', 'QUALE', '③', 0, 0, NULL);

-- 皮肤①②③④
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('SKIN', '皮肤', '皮肤', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('SKIN_1', '完整', '完整', 'SKIN', '①', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('SKIN_2', '擦伤', '擦伤', 'SKIN', '②', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('SKIN_3', '皮疹', '皮疹', 'SKIN', '③', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('SKIN_4', '压疮', '压疮', 'SKIN', '④', 0, 0, NULL);

-- 导管①②③④⑤⑥⑦⑧⑨⑩
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE', '导管', '导管', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_1', '深静脉留置', '深静脉留置', 'PIPE', '①', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_1_a', '颈部', '颈部', 'PIPE_1', 'a', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_1_b', '锁骨下', '锁骨下', 'PIPE_1', 'b', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_1_c', 'PICC', 'PICC', 'PIPE_1', 'c', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_1_d', '输液港', '输液港', 'PIPE_1', 'd', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_1_e', '股静脉', '股静脉', 'PIPE_1', 'e', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_2', '胃管', '胃管', 'PIPE', '②', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_3', '导尿管', '导尿管', 'PIPE', '③', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_4', '止痛泵', '止痛泵', 'PIPE', '④', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_4_a', '硬膜外', '硬膜外', 'PIPE_4', 'a', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_4_b', '静脉', '静脉', 'PIPE_4', 'b', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_5', 'T管', 'T管', 'PIPE', '⑤', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_6', '负压引流', '负压引流', 'PIPE', '⑥', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_7', '气插', '气插', 'PIPE', '⑦', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_8', '气切', '气切', 'PIPE', '⑧', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_9', '胸管', '胸管', 'PIPE', '⑨', 0, 0, NULL);

-- 导管护理√×○
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_NURSE', '导管护理', '导管护理', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_NURSE_1', '已完成并在位通畅', '已完成并在位通畅', 'PIPE_NURSE', '√', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_NURSE_2', '不通畅予以通管', '不通畅予以通管', 'PIPE_NURSE', '×', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PIPE_NURSE_3', '不通畅予以更换', '不通畅予以更换', 'PIPE_NURSE', '○', 0, 0, NULL);

-- 引流液性状序号①②③④⑤⑥⑦⑧⑨⑩
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('FLUID_QUALE', '引流液性状', '引流液性状', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('FLUID_QUALE_1', '清', '清', 'FLUID_QUALE', '①', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('FLUID_QUALE_2', '混浊', '混浊', 'FLUID_QUALE', '②', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('FLUID_QUALE_3', '血性', '血性', 'FLUID_QUALE', '③', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('FLUID_QUALE_4', '淡血性', '淡血性', 'FLUID_QUALE', '④', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('FLUID_QUALE_5', '深黄', '深黄', 'FLUID_QUALE', '⑤', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('FLUID_QUALE_6', '墨绿', '墨绿', 'FLUID_QUALE', '⑥', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('FLUID_QUALE_7', '咖啡色', '咖啡色', 'FLUID_QUALE', '⑦', 0, 0, NULL);

-- 翻身后卧位
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('LIE', '卧位', '卧位', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('LIE_1', '左', '左', 'LIE', '1', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('LIE_2', '平', '平', 'LIE', '2', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('LIE_3', '右', '右', 'LIE', '3', 0, 0, NULL);

-- 入水量项目
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('IN_ITEM', '入水量项目', '入水量项目', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('IN_ITEM_1', '饮水量', '饮水量', 'IN_ITEM', '1', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('IN_ITEM_2', '输液量', '输液量', 'IN_ITEM', '2', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('IN_ITEM_3', '输血量', '输血量', 'IN_ITEM', '3', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('IN_ITEM_4', '食物中的含水量', '食物中的含水量', 'IN_ITEM', '4', 0, 0, NULL);

-- 出水量项目
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM', '出水量项目', '出水量项目', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_1', '尿量', '尿量', 'OUT_ITEM', '1', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_2', '粪便量', '粪便量', 'OUT_ITEM', '2', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_3', '肠胃减压吸出液', '肠胃减压吸出液', 'OUT_ITEM', '3', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_4', '胸腔引流量', '胸腔引流量', 'OUT_ITEM', '4', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_5', '腹腔引流量', '腹腔引流量', 'OUT_ITEM', '5', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_6', '痰液', '痰液', 'OUT_ITEM', '6', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_7', '呕吐液', '呕吐液', 'OUT_ITEM', '7', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_8', '伤口渗出液', '伤口渗出液', 'OUT_ITEM', '8', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OUT_ITEM_9', '胆汁引流液', '胆汁引流液', 'OUT_ITEM', '9', 0, 0, NULL);

-- 服用影响意识或活动的药物
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG', '药物', '药物', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_1', '散瞳剂', '散瞳剂', 'DRUG', '①', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_2', '镇静催眠药', '镇静催眠药', 'DRUG', '②', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_3', '降压药', '降压药', 'DRUG', '③', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_4', '利尿脱水剂', '利尿脱水剂', 'DRUG', '④', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_5', '麻醉止痛药', '麻醉止痛药', 'DRUG', '⑤', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_6', '抗癫痫药', '抗癫痫药', 'DRUG', '⑥', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_7', '抗精神病及抗抑郁药', '抗精神病及抗抑郁药', 'DRUG', '⑦', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_8', '泻药', '泻药', 'DRUG', '⑧', 0, 0, NULL);

-- 用药途径
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_WAY', '用药途径', '用药途径', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_WAY_1', '肌注', '肌注', 'DRUG_WAY', '1', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_WAY_2', '口服', '口服', 'DRUG_WAY', '2', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_WAY_3', '皮下注射', '皮下注射', 'DRUG_WAY', '3', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_WAY_4', '静注', '静注', 'DRUG_WAY', '4', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_WAY_5', '外贴', '外贴', 'DRUG_WAY', '5', 0, 0, NULL);

-- 用药频率
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE', '用药频率', '用药频率', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_1', 'st', 'st', 'DRUG_RATE', '1', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_2', 'qd', 'qd', 'DRUG_RATE', '2', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_3', 'Bid', 'Bid', 'DRUG_RATE', '3', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_4', 'Tid', 'Tid', 'DRUG_RATE', '4', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_5', 'q4h', 'q4h', 'DRUG_RATE', '5', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_6', 'q6h', 'q6h', 'DRUG_RATE', '6', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_7', 'q8h', 'q8h', 'DRUG_RATE', '7', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_8', 'q12h', 'q12h', 'DRUG_RATE', '8', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('DRUG_RATE_9', 'q72h', 'q72h', 'DRUG_RATE', '9', 0, 0, NULL);

-- 职业
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB', '职业', '职业', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_1', '工人', '工人', 'JOB', '1', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_2', '农民', '农民', 'JOB', '2', 0, 2, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_3', '干部', '干部', 'JOB', '3', 0, 3, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_4', '教师', '教师', 'JOB', '4', 0, 4, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_5', '职员', '职员', 'JOB', '5', 0, 5, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_6', '学生', '学生', 'JOB', '6', 0, 6, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_7', '军人', '军人', 'JOB', '7', 0, 7, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_8', '退休', '退休', 'JOB', '8', 0, 8, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_9', '离休', '离休', 'JOB', '9', 0, 9, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_10', '个体', '个体', 'JOB', '10', 0, 10, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_11', '医护', '医护', 'JOB', '11', 0, 11, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_12', '待业', '待业', 'JOB', '12', 0, 12, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('JOB_13', '技术人员', '技术人员', 'JOB', '13', 0, 13, NULL);

-- 关系
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP', '关系', '关系', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_0', '本人', '本人', 'RELATIONSHIP', '0', 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_1', '夫妻', '夫妻', 'RELATIONSHIP', '1', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_2', '父子', '父子', 'RELATIONSHIP', '2', 0, 2, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_3', '父女', '父女', 'RELATIONSHIP', '3', 0, 3, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_4', '母子', '母子', 'RELATIONSHIP', '4', 0, 4, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_5', '母女', '母女', 'RELATIONSHIP', '5', 0, 5, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_6', '兄弟', '兄弟', 'RELATIONSHIP', '6', 0, 6, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_7', '姐妹', '姐妹', 'RELATIONSHIP', '7', 0, 7, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_8', '兄妹', '兄妹', 'RELATIONSHIP', '8', 0, 8, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_9', '姐弟', '姐弟', 'RELATIONSHIP', '9', 0, 9, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_10', '祖孙', '祖孙', 'RELATIONSHIP', '10', 0, 10, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_11', '朋友', '朋友', 'RELATIONSHIP', '11', 0, 11, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_12', '邻居', '邻居', 'RELATIONSHIP', '12', 0, 12, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_13', '亲戚', '亲戚', 'RELATIONSHIP', '13', 0, 13, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_14', '同事', '同事', 'RELATIONSHIP', '14', 0, 14, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RELATIONSHIP_15', '其他', '其他', 'RELATIONSHIP', '15', 0, 15, NULL);

-- 疼痛类型
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_TYPE', '疼痛类型', '疼痛类型', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_TYPE_1', '持续性', '持续性', 'PAIN_TYPE', 'Ⅰ', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_TYPE_2', '阵发性', '阵发性', 'PAIN_TYPE', 'Ⅱ', 0, 2, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_TYPE_3', '间歇性', '间歇性', 'PAIN_TYPE', 'Ⅲ', 0, 3, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_TYPE_4', '进行性加重', '进行性加重', 'PAIN_TYPE', 'Ⅳ', 0, 4, NULL);

-- 疼痛性质
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE', '疼痛性质', '疼痛性质', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE_1', '刀割样痛', '刀割样痛', 'PAIN_QUALE', '①', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE_2', '绞痛', '绞痛', 'PAIN_QUALE', '②', 0, 2, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE_3', '烧灼样痛', '烧灼样痛', 'PAIN_QUALE', '③', 0, 3, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE_4', '刺痛', '刺痛', 'PAIN_QUALE', '④', 0, 4, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE_5', '压痛', '压痛', 'PAIN_QUALE', '⑤', 0, 5, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE_6', '胀痛', '胀痛', 'PAIN_QUALE', '⑥', 0, 6, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE_7', '钝痛', '钝痛', 'PAIN_QUALE', '⑦', 0, 7, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_QUALE_8', '酸痛', '酸痛', 'PAIN_QUALE', '⑧', 0, 8, NULL);

-- 疼痛对患者的影响
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_EFFECT', '疼痛对患者的影响', '疼痛对患者的影响', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_EFFECT_1', '影响睡眠', '影响睡眠', 'PAIN_EFFECT', 'A', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_EFFECT_2', '翻转不安、无法入睡', '翻转不安、无法入睡', 'PAIN_EFFECT', 'B', 0, 2, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_EFFECT_3', '食欲低下', '食欲低下', 'PAIN_EFFECT', 'C', 0, 3, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_EFFECT_4', '生活自理能力（ADL低下）', '生活自理能力（ADL低下）', 'PAIN_EFFECT', 'D', 0, 4, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN_EFFECT_5', '无影响', '无影响', 'PAIN_EFFECT', 'E', 0, 5, NULL);

-- 宣教方式
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_WAY', '宣教方式', '宣教方式', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_WAY_1', '口头讲解', '口头讲解', 'ANNOUNCE_WAY', '①', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_WAY_2', '动作示范', '动作示范', 'ANNOUNCE_WAY', '②', 0, 2, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_WAY_3', '书面资料分发', '书面资料分发', 'ANNOUNCE_WAY', '③', 0, 3, NULL);

-- 宣教对象
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_TARGET', '宣教对象', '宣教对象', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_TARGET_1', '患者', '患者', 'ANNOUNCE_TARGET', '①', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_TARGET_2', '家属', '家属', 'ANNOUNCE_TARGET', '②', 0, 2, NULL);

-- 效果评价
INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_EFFECT', '效果评价', '效果评价', NULL, NULL, 0, 0, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_EFFECT_1', '已掌握，配合好', '已掌握，配合好', 'ANNOUNCE_EFFECT', 'A', 0, 1, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_EFFECT_2', '能复述，能理解，或会演示', '能复述，能理解，或会演示', 'ANNOUNCE_EFFECT', 'B', 0, 2, NULL);

INSERT INTO DICTIONARY_(ID_, NAME_, FULL_NAME_, PARENT_, VALUE_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ANNOUNCE_EFFECT_3', '需强化', '需强化', 'ANNOUNCE_EFFECT', 'C', 0, 3, NULL);


------------------------------------ DOC_MENU_ ----------------------------------------
-- 护理记录
INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RECORD', '护理记录', '护理记录', NULL, '', 0, 0, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('NURSE', '护理记录单', '护理记录单', 'RECORD', '/doc/nurse', 0, 2, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('BASE_NURSE', '基础护理记录单', '基础护理记录单', 'RECORD', '/doc/base', 0, 3, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('BLOOD_SUGAR', '指测血糖监测记录单', '指测血糖监测记录单', 'RECORD', '/doc/bloodSugar', 0, 4, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('RESTRAINT', '使用约束带观察记录表', '使用约束带观察记录表', 'RECORD', '/doc/restraint', 0, 5, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('IN_OUT', '出入液量记录单', '出入液量记录单', 'RECORD', '/doc/inOut', 0, 6, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('OVER', '翻身记录单', '翻身记录单', 'RECORD', '/doc/over', 0, 7, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('HEART', '心电监护记录单', '心电监护记录单', 'RECORD', '/doc/heart', 0, 8, NULL);

-- 护理评估
INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('EVALUATE', '护理评估', '护理评估', NULL, '', 0, 1, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('CHILD_FALL', '儿童跌倒/坠床危险因子评估', '儿童跌倒/坠床危险因子评估', 'EVALUATE', '/doc/childFall', 0, 9, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('ADULT_FALL', '成人跌倒/坠床危险因子评估', '成人跌倒/坠床危险因子评估', 'EVALUATE', '/doc/adultFall', 0, 10, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('BARTHEL', 'Barthel指数评定量表', 'Barthel指数(BL)评定量表', 'EVALUATE', '/doc/barthel', 0, 11, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PRESS', '压疮评估及护理措施表', '压疮评估及护理措施表', 'EVALUATE', '/doc/press', 0, 12, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('PAIN', '疼痛评估记录单', '疼痛评估记录单', 'EVALUATE', '/doc/pain', 0, 13, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('HOSPITALIZE', '护理入院评估单', '护理入院评估单', 'EVALUATE', '/doc/hospitalize', 0, 14, NULL);

INSERT INTO DOC_MENU_(ID_, NAME_, FULL_NAME_, PARENT_, URL_, DELETABLE_, ORDER_, REMARK_)
VALUES ('HEALTH', '健康教育及评估单', '健康教育及评估单', 'EVALUATE', '/doc/health', 0, 15, NULL);
