-- nurse doc
DROP TABLE DOC_LIVER_NURSE_;
DROP TABLE DOC_BARTHEL_;
DROP TABLE DOC_HEART_;
DROP TABLE DOC_IN_OUT_;
DROP TABLE DOC_OVER_;
DROP TABLE DOC_CHILD_FALL_;
DROP TABLE DOC_ADULT_FALL_;
DROP TABLE DOC_PRESS_;
DROP TABLE DOC_RESTRAINT_;
DROP TABLE DOC_PAIN_;
DROP TABLE DOC_NURSE_;
DROP TABLE DOC_BASE_NURSE_;
DROP TABLE DOC_BLOOD_SUGAR_;
DROP TABLE DOC_DATA_;
DROP TABLE DOC_;

-- others
DROP TABLE DIAGNOSIS_;
DROP TABLE DOC_MENU_;
DROP TABLE DICTIONARY_;