CREATE TABLE COM_BED_GROUP(
SEQ_ID BIGINT IDENTITY NOT NULL,
DEPT_CODE	VARCHAR(20),
GROUP_CODE	VARCHAR(20),
GROUP_NAME	VARCHAR(100),
BEDS	VARCHAR(200),
STATUS	CHAR(2),
CREATE_TIME	DATETIME,
UPDATE_TIME	DATETIME,
CREATE_PERSON	VARCHAR(20),
UPDATE_PERSON	VARCHAR(20)
)