CREATE TABLE SCHEDULE_RECORD(
SEQ_ID	BIGINT IDENTITY PRIMARY KEY NOT NULL,
RECORD_CODE	VARCHAR(20),
STATUS	CHAR(2),
START_DATE	VARCHAR(10),
END_DATE	VARCHAR(10),
CREATE_TIME	DATETIME,
UPDATE_TIME	DATETIME,
CREATE_PERSON	VARCHAR(20),
UPDATE_PERSON	VARCHAR(20)

)