CREATE TABLE SCHEDULE_RECORD_DETAIL(
SEQ_ID	BIGINT IDENTITY PRIMARY KEY NOT NULL,
RECORD_CODE	VARCHAR(20),
RECORD_DETAIL_CODE	VARCHAR(20),
STATUS	CHAR(2),
CLASS_CODE	VARCHAR(20),
USER_CODE	VARCHAR(20),
USER_NAME	VARCHAR(100),
USER_LEVEL	VARCHAR(10),
RECORD_DATE	VARCHAR(10),
CREATE_TIME	DATETIME,
UPDATE_TIME	DATETIME,
CREATE_PERSON	VARCHAR(20),
UPDATE_PERSON	VARCHAR(20)
)