CREATE TABLE RESEARCH_PAPER(
SEQ_ID	BIGINT IDENTITY PRIMARY KEY NOT NULL,
DEPT_CODE	VARCHAR(20),
PAPER_NAME	VARCHAR(100),
AUTHOR	VARCHAR(100),
PUBLICTION_NAME	VARCHAR(100),
PUBLICTION_NO	VARCHAR(100),
WORDS_NUMBER	int,
CORE_PUBLICTION	VARCHAR(20),
PUBLISH_DATE	VARCHAR(10),
STATUS	CHAR(2),
CREATE_TIME	DATETIME,
UPDATE_TIME	DATETIME,
CREATE_PERSON	VARCHAR(20),
UPDATE_PERSON	VARCHAR(20)
)