CREATE TABLE RESEARCH_ITEM(
SEQ_ID	BIGINT IDENTITY PRIMARY KEY NOT NULL,
DEPT_CODE	VARCHAR(20),
SUBJECT_NAME	VARCHAR(100),
ITEM_SOURCE	VARCHAR(100),
START_DATE	VARCHAR(10),
END_DATE	VARCHAR(10),
COST	DECIMAL(18,2),
STATUS	CHAR(2),
SUBJECT_HEAD	VARCHAR(100),
SUBJECT_PARTICIPANT	VARCHAR(100),
CREATE_TIME	DATETIME,
UPDATE_TIME	DATETIME,
CREATE_PERSON	VARCHAR(20),
UPDATE_PERSON	VARCHAR(20)
)