package com.lachesis.mnis.core.identity.entity;

import java.util.Date;

public class UserSession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.session_id
     *
     * @mbggenerated
     */
    private Integer sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.logon_datetime
     *
     * @mbggenerated
     */
    private Date logonDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.last_op_datetime
     *
     * @mbggenerated
     */
    private Date lastOpDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.client_ip
     *
     * @mbggenerated
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.client_os
     *
     * @mbggenerated
     */
    private String clientOs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.alive
     *
     * @mbggenerated
     */
    private Integer alive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.session_id
     *
     * @return the value of user_session.session_id
     *
     * @mbggenerated
     */
    public Integer getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.session_id
     *
     * @param sessionId the value for user_session.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.user_id
     *
     * @return the value of user_session.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.user_id
     *
     * @param userId the value for user_session.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.token
     *
     * @return the value of user_session.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.token
     *
     * @param token the value for user_session.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.logon_datetime
     *
     * @return the value of user_session.logon_datetime
     *
     * @mbggenerated
     */
    public Date getLogonDatetime() {
        return logonDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.logon_datetime
     *
     * @param logonDatetime the value for user_session.logon_datetime
     *
     * @mbggenerated
     */
    public void setLogonDatetime(Date logonDatetime) {
        this.logonDatetime = logonDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.last_op_datetime
     *
     * @return the value of user_session.last_op_datetime
     *
     * @mbggenerated
     */
    public Date getLastOpDatetime() {
        return lastOpDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.last_op_datetime
     *
     * @param lastOpDatetime the value for user_session.last_op_datetime
     *
     * @mbggenerated
     */
    public void setLastOpDatetime(Date lastOpDatetime) {
        this.lastOpDatetime = lastOpDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.client_ip
     *
     * @return the value of user_session.client_ip
     *
     * @mbggenerated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.client_ip
     *
     * @param clientIp the value for user_session.client_ip
     *
     * @mbggenerated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.client_os
     *
     * @return the value of user_session.client_os
     *
     * @mbggenerated
     */
    public String getClientOs() {
        return clientOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.client_os
     *
     * @param clientOs the value for user_session.client_os
     *
     * @mbggenerated
     */
    public void setClientOs(String clientOs) {
        this.clientOs = clientOs == null ? null : clientOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.alive
     *
     * @return the value of user_session.alive
     *
     * @mbggenerated
     */
    public Integer getAlive() {
        return alive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.alive
     *
     * @param alive the value for user_session.alive
     *
     * @mbggenerated
     */
    public void setAlive(Integer alive) {
        this.alive = alive;
    }
}