----------------------------南方医院-------------------------------------------------------------
USE [MNIS_V3]
GO
/****** Object:  Table [dbo].[SYS_CONFIG]    Script Date: 11/12/2015 14:45:03 ******/
/****************************初始化系统设置************************************/
SET IDENTITY_INSERT [dbo].[SYS_CONFIG] ON
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (1, N'temperatureChartLabel', N'{"breath":1,"bloodPress":1,"totalInput":1,"stool":1,"urine":1,"otherOutput":1,"height":1,"weight":1,"skinTest":1,"other":1}', N'S', N'', N'1', N'')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (2, N'isSortBedList', N'Y', N'S', N'', N'1', N'是否按床位号排序')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (3, N'temperatureChart', N'{"names": {"date": "日期","hod": "住院天数","operation": "手术后天数","time": "时间","temperature": "体温","pulse": "脉搏","temperatureUnit": "体温单位","pulseUnit": "脉搏单位","breath": "呼吸","bloodPress": "血压","totalInput": "总入量","totalOutput": "总出量","stool": "大便次数","weight": "体重","height": "身高","pain": "疼痛强度","output_label": "排出量","skinTest": "皮试","other":"其他","otherOutput":"其它出量(ml)","urine":"尿量"},"timeTitle": "2,6,10,14,18,22","tempsheetItems": "pain,breath,bloodPress,totalInput,stool,urine,otherOutput,height,weight,skinTest,other","times": {"breath": 6,"bloodPress": 2}}', N'S', N'', N'1', N'三测单绘制')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (4, N'functionMenuIds', N'205,213,219,210,209,303,309,307,308', N'S', N'', N'1', N'菜单')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (5, N'tempInputItemsBase', N'date,time,temperature,cooledTemperature,pulse,heartRate,breath,bloodPress', N'S', N'', N'1', N'【体征录入-基本体征】NDA')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (6, N'tempInputItemsOther', N'otherOutput,totalInput,urine,stool,weight,event,remark,skinTest,other', N'S', N'', N'1', N'【体征录入-其他体征】NDA')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (7, N'tempNaviTitles', N'基本体征,出入量及其他', N'S', N'', N'1', N'【体征录入-导航标题】')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (8, N'tempInputItems', N'temperature,pulse,heartRate,breath,bloodPress,totalOutput,output,totalInput,urine,stool,pain,height,weight,skinTest,event,remark,other,otherOutput', N'S', N'', N'1', N'【体征录入】的项目及项目顺序')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (9, N'tempInputTimeShow', N'false', N'S', N'', N'1', N'【体征录入】是否需要时间弹出框')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (10, N'tempInputTimeSelector', N'01:00,02:00,03:00,04:00,05:00,06:00,07:00,08:00,09:00,10:00,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,19:00,20:00,21:00,22:00,23:00,24:00', N'S', N'', N'1', N'【体征录入】时间选项')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (11, N'tempsheetItems', N'totalInput,stool,urine,otherOutput,weight,skintest,other', N'S', N'', N'1', N'三测得上各项目的显示顺序')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (12, N'hospitalName', N'南方医院', N'S', N'', N'1', N'医院名称')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (13, N'canEditSignTime', N'false', N'S', N'', N'1', N'【体征修改】true：可以从时间弹出框设置；false：只能选')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (14, N'hospitalCode', N'SZ_SY', N'S', N'', N'1', N'医院代码')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (15, N'comSkinTestDrugs', N'青霉素,新朗欧,头孢孟多酯,特治星,罗氏芬,头孢呋辛,头孢他啶,舒普深,链霉素,特殊值', N'S', N'', N'1', N'【体征录入】皮试常用药物')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (16, N'comSkinTestDrugsFirstLet', N'qms,xlo,tbmdz,tzx,lsf,tbfx,tbtd,sps,lms,ts', N'S', N'', N'1', N'【体征录入】皮试药物首字母')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (18, N'labelBarcodeType', N'1', N'S', N'', N'1', N'瓶签纵向和横向打印类型(0:横向,1:纵向)')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (19, N'encryptType', N'0', N'S', N'', N'1', N'密码是否加密(1:是,0:否)')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (23, N'pcMenuIds', N'menu-1,menu-2,menu-3,menu-5,menu-9,menu-7,menu-8', N'S', N'', N'1', N'PC端菜单显示设置')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (24, N'nurseShiftTime', N'0,8,16', N'S', N'', N'1', N'交班本时间点')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (26, N'liquorOrderType', N'0', N'S', N'', N'1', N'配液管理是否需要长嘱(0:临嘱,1:长嘱,2:全部)')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (27, N'isOpenIS', N'0', N'S', N'', N'1', N'是否开启输液管理系统功能')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (28, N'isSyncDocReport', N'0', N'S', N'', N'1', N'医嘱,生命体征是否同步到文书')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (29, N'infusionEnable', N'0', N'S', N'', N'1', N'是否开启输液管理系统功能')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (30, N'infusionDeviceSetting', N'{"alarmSwitch":"0","restMlAlerm":"10","dropSpeedFloor":"20","dropSpeedUpper":"60","restTimeAlarm":"5","idc":"15"}', N'S', NULL, N'1', N'默认输液监测设备配置息')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (31, N'siTime', N'{"cod": "time","jsnPth": "time","max": 0,"min": 0,"nam": "时间","unt": "","inptTyp": "TP_TIME","opts": [{"refid": "t1","isNum": "11","isShowText": "1","max": "0","min": "0","nam": "02:00"},{"refid": "t2","isNum": "11","isShowText": "1","max": "0","min": "0","nam": "06:00"},{"refid": "t3","isNum": "11","isShowText": "1","max": "0","min": "0","nam": "10:00"},{"refid": "t4","isNum": "11","isShowText": "1","max": "0","min": "0","nam": "14:00"},{"refid": "t5","isNum": "11","isShowText": "1","max": "0","min": "0","nam": "18:00"},{"refid": "t6","isNum": "11","isShowText": "1","max": "0","min": "0","nam": "22:00"}]}', N'S', NULL, N'1', N'体温单录入时间控制')
INSERT [dbo].[SYS_CONFIG] ([ID], [CONFIG_ID], [CONFIG_VALUE], [CONFIG_TYPE], [CONFIG_OWNER], [VALID_FLAG], [CONFIG_DESC]) VALUES (34, N'CZPrintTime', N'18:00', N'S', N'', N'1', N'长嘱提前打印时间(静注等)')
SET IDENTITY_INSERT [dbo].[SYS_CONFIG] OFF
/****** Object:  Table [dbo].[DIC_FREQ]    Script Date: 11/12/2015 14:45:03 ******/
/****************************初始化医嘱频次************************************/
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/12小时', N'1/12小时', N'1', NULL, 2, N'08:00-16:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/1小时', N'1/1小时', N'1', NULL, 24, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/2小时', N'1/2小时', N'1', NULL, 12, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/3小时', N'1/3小时', N'1', NULL, 8, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/4小时', N'1/4小时', N'1', NULL, 6, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/6小时', N'1/6小时', N'1', NULL, 4, N'06:00-12:00-18:00-24:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/8小时', N'1/8小时', N'1', NULL, 3, N'08:00-16:00-24:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/日', N'1/日', N'1', NULL, 1, N'08:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/晚', N'1/晚', N'1', NULL, 1, N'17:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/午', N'1/午', N'1', NULL, 1, N'12:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'1/早', N'1/早', N'1', NULL, 1, N'07:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'2/日', N'2/日', N'1', NULL, 2, N'08:00-16:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'3/日', N'3/日', N'1', NULL, 3, N'08:00-16:00-24:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'4/日', N'4/日', N'1', NULL, 4, N'06:00-12:00-18:00-24:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'6/日', N'6/日', N'1', NULL, 6, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'7/日', N'7/日', N'1', NULL, 7, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'df', N'顿服', N'1', NULL, 1, N'08:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'df2', N'顿服', N'1', NULL, 2, N'12:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'df3', N'顿服', N'1', NULL, 3, N'18:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'ls', N'LS', N'1', NULL, 1, N'12:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'prn', N'prn', N'1', NULL, 1, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q10m', N'q10m', N'1', NULL, 144, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q12h', N'q12h', N'1', NULL, 2, N'8:00-20:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q15m', N'q15m', N'1', NULL, 96, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q1h', N'q1h', N'1', NULL, 24, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q2h', N'q2h', N'1', NULL, 12, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q30m', N'q30m', N'1', NULL, 48, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q3h', N'q3h', N'1', NULL, 8, N'00:00-03:00-06:00-09:00-12:00-15:00-18:00-21:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q4h', N'q4h', N'1', NULL, 6, N'00:00-04:00-8:00-12:00-16:00-20:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q5m', N'q5m', N'1', NULL, 288, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q6h', N'q6h', N'1', NULL, 4, N'0:00-6:00-12:00-18:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'q8h', N'q8h', N'1', NULL, 3, N'0:00-8:00-16:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'qd', N'qd', N'1', NULL, 1, N'12:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'qid', N'qid', N'1', NULL, 4, N'00:00-04:00-8:00-12:00-16:00-20:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'qm', N'qm', N'1', NULL, 1, N'08:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'qn', N'qn', N'1', NULL, 1, N'20:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'qod', N'qod', N'1', NULL, 1, N'08', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'qw', N'qw', N'1', NULL, 1, N'08:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'sos', N'sos', N'1', NULL, 1, N'0：00-12:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'st', N'st', N'1', NULL, 1, N'08:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'sy', N'sy', N'1', NULL, 1, N'', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'tid', N'tid', N'1', NULL, 3, N'8:00-12:00-16:00', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'tiw', N'Tiw', N'1', NULL, 1, N'08', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'持续', N'持续', N'1', NULL, 1, N'08', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'日两次', N'日两次', N'1', NULL, 2, N'1', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'日三次', N'日三次', N'1', NULL, 3, N'1', N'-')
INSERT [dbo].[DIC_FREQ] ([FREQ_CODE], [FREQ_NAME], [FLAG], [MODIFY_DATE], [FREQUENCY], [FREQUENCY_TIME], [TIME_TAG]) VALUES (N'日一次', N'日一次', N'1', NULL, 1, N'1', N'-')
/****** Object:  Table [dbo].[DIC_BODY_SIGN]    Script Date: 11/12/2015 14:45:03 ******/
/****************************初始化生命体征项************************************/
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'remark', N'备注', NULL)
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'abdominalCir', N'腹围', N'cm')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'bloodGlu', N'指测血糖', N'mmol/L')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'bloodPress', N'血压', N'mmHg')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'breath', N'呼吸', N'次/分')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'cooledTemperature', N'降温后体温', N'°C')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'heartRate', N'心率', N'次/分')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'height', N'身高', N'cm')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'inTake', N'入量', N'ml')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'other', N'其它', NULL)
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'otherOutput', N'其他出量', N'ml')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'oxygenSaturation', N'血氧饱和度', N'%')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'pain', N'疼痛', N'级')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'pulse', N'脉搏', N'次/分')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'stool', N'大便次数', N'次')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'temperature', N'体温', N'°C')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'totalInput', N'总入量', N'ml')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'totalOutput', N'总出量', N'ml')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'urine', N'尿量', N'ml')
INSERT [dbo].[DIC_BODY_SIGN] ([ITEM_CODE], [ITEM_NAME], [ITEM_UNIT]) VALUES (N'weight', N'体重', N'kg')
/****** Object:  Table [dbo].[COM_DIC]    Script Date: 11/12/2015 14:45:03 ******/
/****************************初始化费用类型和医嘱类型************************************/
SET IDENTITY_INSERT [dbo].[COM_DIC] ON
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (57, N'CHARGE', N'0', N'自费', N'自费', N'自费', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (58, N'CHARGE', N'0', N'自费', N'自费绿卡', N'自费绿卡', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (59, N'CHARGE', N'0', N'自费', N'免号自费', N'免号自费', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (60, N'CHARGE', N'1', N'医保', N'肇庆医保', N'肇庆医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (61, N'CHARGE', N'1', N'医保', N'潮州医保', N'潮州医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (62, N'CHARGE', N'1', N'医保', N'医疗保险', N'医疗保险', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (63, N'CHARGE', N'1', N'医保', N'广州医保', N'广州医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (64, N'CHARGE', N'1', N'医保', N'东莞医保', N'东莞医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (65, N'CHARGE', N'1', N'医保', N'汕尾医保', N'汕尾医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (66, N'CHARGE', N'1', N'医保', N'中山医保', N'中山医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (67, N'CHARGE', N'1', N'医保', N'佛山医保', N'佛山医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (68, N'CHARGE', N'1', N'医保', N'南昌医保', N'南昌医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (69, N'CHARGE', N'1', N'医保', N'惠州医保', N'惠州医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (70, N'CHARGE', N'1', N'医保', N'萝岗医保', N'萝岗医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (71, N'CHARGE', N'1', N'医保', N'珠海医保', N'珠海医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (72, N'CHARGE', N'1', N'医保', N'农医保', N'农医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (73, N'CHARGE', N'1', N'医保', N'医保50%', N'医保50%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (74, N'CHARGE', N'1', N'医保', N'医保60%', N'医保60%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (75, N'CHARGE', N'1', N'医保', N'韶关医保', N'韶关医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (76, N'CHARGE', N'1', N'医保', N'江门医保', N'江门医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (77, N'CHARGE', N'1', N'医保', N'内保10%', N'内保10%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (78, N'CHARGE', N'1', N'医保', N'内保15%', N'内保15%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (79, N'CHARGE', N'1', N'医保', N'内保20%', N'内保20%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (80, N'CHARGE', N'1', N'医保', N'医保欠费', N'医保欠费', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (81, N'CHARGE', N'1', N'医保', N'清远医保', N'清远医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (82, N'CHARGE', N'1', N'医保', N'省网医保', N'省网医保', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (83, N'CHARGE', N'2', N'公费', N'省公费', N'省公费', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (84, N'CHARGE', N'2', N'公费', N'公费5%', N'公费5%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (85, N'CHARGE', N'2', N'公费', N'公费10%', N'公费10%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (86, N'CHARGE', N'2', N'公费', N'公费20%', N'公费20%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (87, N'CHARGE', N'2', N'公费', N'Z公费20%', N'Z公费20%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (88, N'CHARGE', N'2', N'公费', N'Z公费10%', N'Z公费10%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (89, N'CHARGE', N'2', N'公费', N'Z公费5%', N'Z公费5%', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (90, N'CHARGE', N'2', N'公费', N'公费', N'公费', N'1', 0, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (91, N'USAGE', N'INFUSION', N'输液', N'VD*', N'VD*', N'1', 800, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (92, N'USAGE', N'INFUSION', N'输液', N'VD', N'VD', N'1', 895, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (93, N'USAGE', N'INFUSION', N'输液', N'VD,输液泵', N'VD,输液泵', N'1', 893, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (94, N'USAGE', N'INFUSION', N'输液', N'VD,透析中', N'VD,透析中', N'1', 892, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (95, N'USAGE', N'INFUSION', N'输液', N'VD,透析后', N'VD,透析后', N'1', 891, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (96, N'USAGE', N'INFUSION', N'输液', N'VD,输液泵维持', N'VD,输液泵维持', N'1', 890, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (97, N'USAGE', N'INFUSION', N'输液', N'VD,加入液体', N'VD,加入液体', N'1', 889, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (98, N'USAGE', N'INFUSION', N'输液', N'VD,加入三升袋', N'VD,加入三升袋', N'1', 888, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (99, N'USAGE', N'INFUSION', N'输液', N'VD*,输液泵', N'VD*,输液泵', N'1', 800, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (100, N'USAGE', N'INFUSION', N'输液', N'VD*,输液泵维持', N'VD*,输液泵维持', N'1', 800, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (101, N'USAGE', N'INFUSION', N'输液', N'VD*,加入三升袋', N'VD*,加入三升袋', N'1', 800, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (102, N'USAGE', N'INFUSION', N'输液', N'VD,(冲管)', N'VD,(冲管)', N'1', 894, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (103, N'USAGE', N'INFUSION', N'输液', N'VD,(避光)', N'VD,(避光)', N'1', 887, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (104, N'USAGE', N'INFUSION', N'输液', N'VD*,(避光)', N'VD*,(避光)', N'1', 800, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (105, N'USAGE', N'INFUSION', N'输液', N'VD,(慢)', N'VD,(慢)', N'1', 886, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (106, N'USAGE', N'INFUSION', N'输液', N'VD*,(慢)', N'VD*,(慢)', N'1', 800, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (107, N'USAGE', N'INFUSION', N'输液', N'VD（抗肿瘤药）', N'VD（抗肿瘤药）', N'1', 885, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (108, N'USAGE', N'INFUSION', N'输液', N'VD*(抗肿瘤药)', N'VD*(抗肿瘤药)', N'1', 800, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (109, N'USAGE', N'INFUSION', N'输液', N'VD输血', N'VD输血', N'1', 884, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (110, N'USAGE', N'INFUSION', N'输液', N'VD*输血', N'VD*输血', N'1', 800, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (111, N'USAGE', N'INFUSION', N'输液', N'IV', N'IV', N'1', 899, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (112, N'USAGE', N'INFUSION', N'输液', N'IV,微量泵', N'IV,微量泵', N'1', 898, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (113, N'USAGE', N'INFUSION', N'输液', N'IV,透析后', N'IV,透析后', N'1', 897, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (114, N'USAGE', N'INFUSION', N'输液', N'IV,冲管', N'IV,冲管', N'1', 896, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (115, N'USAGE', N'INJECT', N'注射', N'IM', N'IM', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (116, N'USAGE', N'INJECT', N'注射', N'IM,术前30', N'IM,术前30', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (117, N'USAGE', N'INJECT', N'注射', N'皮下注射', N'皮下注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (118, N'USAGE', N'INJECT', N'注射', N'脱敏注射', N'脱敏注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (119, N'USAGE', N'INJECT', N'注射', N'脐静脉注射', N'脐静脉注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (120, N'USAGE', N'INJECT', N'注射', N'心内注射', N'心内注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (121, N'USAGE', N'INJECT', N'注射', N'胸腔注射', N'胸腔注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (122, N'USAGE', N'INJECT', N'注射', N'皮内注射', N'皮内注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (123, N'USAGE', N'INJECT', N'注射', N'动脉注射', N'动脉注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (124, N'USAGE', N'INJECT', N'注射', N'宫颈注射', N'宫颈注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (125, N'USAGE', N'INJECT', N'注射', N'后穹隆盆腔内注射', N'后穹隆盆腔内注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (126, N'USAGE', N'INJECT', N'注射', N'球后注射', N'球后注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (127, N'USAGE', N'INJECT', N'注射', N'结膜下注射', N'结膜下注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (128, N'USAGE', N'INJECT', N'注射', N'半球后注射', N'半球后注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (129, N'USAGE', N'INJECT', N'注射', N'锁骨上V注射', N'锁骨上V注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (130, N'USAGE', N'INJECT', N'注射', N'穴位注射', N'穴位注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (131, N'USAGE', N'INJECT', N'注射', N'药泵内注射', N'药泵内注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (132, N'USAGE', N'INJECT', N'注射', N'注射部位环形封闭', N'注射部位环形封闭', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (133, N'USAGE', N'INJECT', N'注射', N'腹壁皮下注射', N'腹壁皮下注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (134, N'USAGE', N'INJECT', N'注射', N'脑室内注射', N'脑室内注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (135, N'USAGE', N'INJECT', N'注射', N'腹部皮下注射', N'腹部皮下注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (136, N'USAGE', N'INJECT', N'注射', N'羊膜腔内注射', N'羊膜腔内注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (137, N'USAGE', N'INJECT', N'注射', N'鞘内注射', N'鞘内注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (138, N'USAGE', N'INJECT', N'注射', N'瘤体内注射', N'瘤体内注射', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (139, N'USAGE', N'ORAL', N'口服药', N'研磨口服', N'研磨口服', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (140, N'USAGE', N'ORAL', N'口服药', N'舌下含服', N'舌下含服', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (141, N'USAGE', N'ORAL', N'口服药', N'口服', N'口服', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (142, N'USAGE', N'ORAL', N'口服药', N'口服(餐前)', N'口服(餐前)', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (143, N'USAGE', N'ORAL', N'口服药', N'口服(自服)', N'口服(自服)', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (144, N'USAGE', N'ORAL', N'口服药', N'口服(必要时)', N'口服(必要时)', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (145, N'USAGE', N'ORAL', N'口服药', N'口服(晚睡前)', N'口服(晚睡前)', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (146, N'USAGE', N'ORAL', N'口服药', N'冲服', N'冲服', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (147, N'USAGE', N'ORAL', N'口服药', N'泡服', N'泡服', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (148, N'USAGE', N'ORAL', N'口服药', N'嚼服', N'嚼服', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (149, N'USAGE', N'ORAL', N'口服药', N'先煎', N'先煎', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (150, N'USAGE', N'ORAL', N'口服药', N'后下', N'后下', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (151, N'USAGE', N'ORAL', N'口服药', N'包煎', N'包煎', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (152, N'USAGE', N'ORAL', N'口服药', N'烊化', N'烊化', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (153, N'USAGE', N'ORAL', N'口服药', N'泡服', N'泡服', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (154, N'USAGE', N'ORAL', N'口服药', N'另溶', N'另溶', N'1', 1000, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (155, N'USAGE', N'SKINTEST', N'皮试', N'皮试用', N'皮试用', N'1', 700, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (156, N'USAGE', N'SKINTEST', N'皮试', N'试敏用', N'试敏用', N'1', 700, NULL)
GO
print 'Processed 100 total records'
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (157, N'USAGE', N'UZ', N'治疗', N'经空肠造瘘管注入', N'经空肠造瘘管注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (158, N'USAGE', N'UZ', N'治疗', N'胃管注入', N'胃管注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (159, N'USAGE', N'UZ', N'治疗', N'胃管冲洗', N'胃管冲洗', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (160, N'USAGE', N'UZ', N'治疗', N'膀胱冲洗', N'膀胱冲洗', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (161, N'USAGE', N'UZ', N'治疗', N'气管内滴药', N'气管内滴药', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (162, N'USAGE', N'UZ', N'治疗', N'气管内滴入', N'气管内滴入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (163, N'USAGE', N'UZ', N'治疗', N'雾化吸入', N'雾化吸入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (164, N'USAGE', N'UZ', N'治疗', N'经胃造瘘管注入', N'经胃造瘘管注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (165, N'USAGE', N'UZ', N'治疗', N'滴双眼', N'滴双眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (166, N'USAGE', N'UZ', N'治疗', N'滴右鼻', N'滴右鼻', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (167, N'USAGE', N'UZ', N'治疗', N'滴左鼻', N'滴左鼻', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (168, N'USAGE', N'UZ', N'治疗', N'滴双鼻', N'滴双鼻', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (169, N'USAGE', N'UZ', N'治疗', N'滴左耳', N'滴左耳', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (170, N'USAGE', N'UZ', N'治疗', N'滴右耳', N'滴右耳', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (171, N'USAGE', N'UZ', N'治疗', N'滴双耳', N'滴双耳', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (172, N'USAGE', N'UZ', N'治疗', N'滴左眼', N'滴左眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (173, N'USAGE', N'UZ', N'治疗', N'滴右眼', N'滴右眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (174, N'USAGE', N'UZ', N'治疗', N'湿敷', N'湿敷', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (175, N'USAGE', N'UZ', N'治疗', N'肛注', N'肛注', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (176, N'USAGE', N'UZ', N'治疗', N'喷喉', N'喷喉', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (177, N'USAGE', N'UZ', N'治疗', N'喷鼻', N'喷鼻', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (178, N'USAGE', N'UZ', N'治疗', N'含漱', N'含漱', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (179, N'USAGE', N'UZ', N'治疗', N'涂右眼', N'涂右眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (180, N'USAGE', N'UZ', N'治疗', N'涂左眼', N'涂左眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (181, N'USAGE', N'UZ', N'治疗', N'涂双眼', N'涂双眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (182, N'USAGE', N'UZ', N'治疗', N'坐浴', N'坐浴', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (183, N'USAGE', N'UZ', N'治疗', N'擦浴', N'擦浴', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (184, N'USAGE', N'UZ', N'治疗', N'涂患处', N'涂患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (185, N'USAGE', N'UZ', N'治疗', N'A药盒注入', N'A药盒注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (186, N'USAGE', N'UZ', N'治疗', N'洗双耳', N'洗双耳', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (187, N'USAGE', N'UZ', N'治疗', N'洗右外耳道', N'洗右外耳道', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (188, N'USAGE', N'UZ', N'治疗', N'洗右耳', N'洗右耳', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (189, N'USAGE', N'UZ', N'治疗', N'洗左外耳道', N'洗左外耳道', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (190, N'USAGE', N'UZ', N'治疗', N'洗左耳', N'洗左耳', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (191, N'USAGE', N'UZ', N'治疗', N'涂口腔', N'涂口腔', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (192, N'USAGE', N'UZ', N'治疗', N'涂创面', N'涂创面', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (193, N'USAGE', N'UZ', N'治疗', N'V药盒注入', N'V药盒注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (194, N'USAGE', N'UZ', N'治疗', N'胸腔冲洗', N'胸腔冲洗', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (195, N'USAGE', N'UZ', N'治疗', N'(左腹股沟)', N'(左腹股沟)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (196, N'USAGE', N'UZ', N'治疗', N'皮下(晚餐前)', N'皮下(晚餐前)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (197, N'USAGE', N'UZ', N'治疗', N'皮下(中餐前)', N'皮下(中餐前)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (198, N'USAGE', N'UZ', N'治疗', N'皮下,透析中', N'皮下,透析中', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (199, N'USAGE', N'UZ', N'治疗', N'皮下(早餐前)', N'皮下(早餐前)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (200, N'USAGE', N'UZ', N'治疗', N'心前区外贴', N'心前区外贴', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (201, N'USAGE', N'UZ', N'治疗', N'腹膜透析', N'腹膜透析', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (202, N'USAGE', N'UZ', N'治疗', N'冲洗左眼', N'冲洗左眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (203, N'USAGE', N'UZ', N'治疗', N'冲洗右眼', N'冲洗右眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (204, N'USAGE', N'UZ', N'治疗', N'冲洗双眼', N'冲洗双眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (205, N'USAGE', N'UZ', N'治疗', N'(右腹股沟)', N'(右腹股沟)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (206, N'USAGE', N'UZ', N'治疗', N'鼻饲', N'鼻饲', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (207, N'USAGE', N'UZ', N'治疗', N'氧气雾化吸入', N'氧气雾化吸入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (208, N'USAGE', N'UZ', N'治疗', N'肾盂冲洗', N'肾盂冲洗', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (209, N'USAGE', N'UZ', N'治疗', N'从肝A插管滴入', N'从肝A插管滴入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (210, N'USAGE', N'UZ', N'治疗', N'(双前臂)', N'(双前臂)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (211, N'USAGE', N'UZ', N'治疗', N'颈V灌注及封闭', N'颈V灌注及封闭', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (212, N'USAGE', N'UZ', N'治疗', N'门V药盒注入', N'门V药盒注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (213, N'USAGE', N'UZ', N'治疗', N'皮下(颞浅A旁)', N'皮下(颞浅A旁)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (214, N'USAGE', N'UZ', N'治疗', N'肝A药盒注入', N'肝A药盒注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (215, N'USAGE', N'UZ', N'治疗', N'骶管封闭', N'骶管封闭', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (216, N'USAGE', N'UZ', N'治疗', N'疤痕封闭', N'疤痕封闭', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (217, N'USAGE', N'UZ', N'治疗', N'灌肠', N'灌肠', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (218, N'USAGE', N'UZ', N'治疗', N'清洁灌肠', N'清洁灌肠', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (219, N'USAGE', N'UZ', N'治疗', N'保留灌肠', N'保留灌肠', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (220, N'USAGE', N'UZ', N'治疗', N'腹腔注入', N'腹腔注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (221, N'USAGE', N'UZ', N'治疗', N'可控膀胱冲洗', N'可控膀胱冲洗', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (222, N'USAGE', N'UZ', N'治疗', N'不保留灌肠', N'不保留灌肠', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (223, N'USAGE', N'UZ', N'治疗', N'腹腔内注入', N'腹腔内注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (224, N'USAGE', N'UZ', N'治疗', N'洗胃', N'洗胃', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (225, N'USAGE', N'UZ', N'治疗', N'伤口冲洗', N'伤口冲洗', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (226, N'USAGE', N'UZ', N'治疗', N'(造影用药)', N'(造影用药)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (227, N'USAGE', N'UZ', N'治疗', N'(术中用药)', N'(术中用药)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (228, N'USAGE', N'UZ', N'治疗', N'左下肢CPM', N'左下肢CPM', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (229, N'USAGE', N'UZ', N'治疗', N'右下肢CPM', N'右下肢CPM', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (230, N'USAGE', N'UZ', N'治疗', N'双下肢CPM', N'双下肢CPM', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (231, N'USAGE', N'UZ', N'治疗', N'(左上肢)', N'(左上肢)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (232, N'USAGE', N'UZ', N'治疗', N'(左手)', N'(左手)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (233, N'USAGE', N'UZ', N'治疗', N'(头部)', N'(头部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (234, N'USAGE', N'UZ', N'治疗', N'(右上肢)', N'(右上肢)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (235, N'USAGE', N'UZ', N'治疗', N'(右手)', N'(右手)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (236, N'USAGE', N'UZ', N'治疗', N'(右下肢)', N'(右下肢)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (237, N'USAGE', N'UZ', N'治疗', N'(右脚)', N'(右脚)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (238, N'USAGE', N'UZ', N'治疗', N'(左脚)', N'(左脚)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (239, N'USAGE', N'UZ', N'治疗', N'(左下肢)', N'(左下肢)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (240, N'USAGE', N'UZ', N'治疗', N'(胸部)', N'(胸部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (241, N'USAGE', N'UZ', N'治疗', N'(左胸部)', N'(左胸部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (242, N'USAGE', N'UZ', N'治疗', N'(右胸部)', N'(右胸部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (243, N'USAGE', N'UZ', N'治疗', N'(四肢)', N'(四肢)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (244, N'USAGE', N'UZ', N'治疗', N'(左侧)', N'(左侧)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (245, N'USAGE', N'UZ', N'治疗', N'(右侧)', N'(右侧)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (246, N'USAGE', N'UZ', N'治疗', N'(双侧)', N'(双侧)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (247, N'USAGE', N'UZ', N'治疗', N'(腹部)', N'(腹部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (248, N'USAGE', N'UZ', N'治疗', N'(左腹部)', N'(左腹部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (249, N'USAGE', N'UZ', N'治疗', N'(右腹部)', N'(右腹部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (250, N'USAGE', N'UZ', N'治疗', N'(左下腹部)', N'(左下腹部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (251, N'USAGE', N'UZ', N'治疗', N'(右下腹部)', N'(右下腹部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (252, N'USAGE', N'UZ', N'治疗', N'(左大腿)', N'(左大腿)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (253, N'USAGE', N'UZ', N'治疗', N'(右大腿)', N'(右大腿)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (254, N'USAGE', N'UZ', N'治疗', N'(左小腿)', N'(左小腿)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (255, N'USAGE', N'UZ', N'治疗', N'(右小腿)', N'(右小腿)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (256, N'USAGE', N'UZ', N'治疗', N'(双上肢)', N'(双上肢)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (257, N'USAGE', N'UZ', N'治疗', N'(双下肢)', N'(双下肢)', N'1', 600, NULL)
GO
print 'Processed 200 total records'
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (258, N'USAGE', N'UZ', N'治疗', N'(双手)', N'(双手)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (259, N'USAGE', N'UZ', N'治疗', N'(双脚)', N'(双脚)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (260, N'USAGE', N'UZ', N'治疗', N'(背部)', N'(背部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (261, N'USAGE', N'UZ', N'治疗', N'(臀部)', N'(臀部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (262, N'USAGE', N'UZ', N'治疗', N'(右臀部)', N'(右臀部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (263, N'USAGE', N'UZ', N'治疗', N'(左臀部)', N'(左臀部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (264, N'USAGE', N'UZ', N'治疗', N'(双腋下)', N'(双腋下)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (265, N'USAGE', N'UZ', N'治疗', N'(左腋下)', N'(左腋下)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (266, N'USAGE', N'UZ', N'治疗', N'(右腋下)', N'(右腋下)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (267, N'USAGE', N'UZ', N'治疗', N'(双腹股沟)', N'(双腹股沟)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (268, N'USAGE', N'UZ', N'治疗', N'(右前臂)', N'(右前臂)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (269, N'USAGE', N'UZ', N'治疗', N'(左前臂)', N'(左前臂)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (270, N'USAGE', N'UZ', N'治疗', N'(双上臂)', N'(双上臂)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (271, N'USAGE', N'UZ', N'治疗', N'(左上臂)', N'(左上臂)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (272, N'USAGE', N'UZ', N'治疗', N'(右上臂)', N'(右上臂)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (273, N'USAGE', N'UZ', N'治疗', N'(左肱动脉)', N'(左肱动脉)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (274, N'USAGE', N'UZ', N'治疗', N'(右肱动脉)', N'(右肱动脉)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (275, N'USAGE', N'UZ', N'治疗', N'冲洗鼻腔', N'冲洗鼻腔', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (276, N'USAGE', N'UZ', N'治疗', N'洗双外耳道', N'洗双外耳道', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (277, N'USAGE', N'UZ', N'治疗', N'(左右肱动脉)', N'(左右肱动脉)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (278, N'USAGE', N'UZ', N'治疗', N'(躯干)', N'(躯干)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (279, N'USAGE', N'UZ', N'治疗', N'尿道支架管滴入', N'尿道支架管滴入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (280, N'USAGE', N'UZ', N'治疗', N'(颈部)', N'(颈部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (281, N'USAGE', N'UZ', N'治疗', N'(左颈部)', N'(左颈部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (282, N'USAGE', N'UZ', N'治疗', N'(右颈部)', N'(右颈部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (283, N'USAGE', N'UZ', N'治疗', N'椎管内注入', N'椎管内注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (284, N'USAGE', N'UZ', N'治疗', N'足三里封闭', N'足三里封闭', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (285, N'USAGE', N'UZ', N'治疗', N'(间断)', N'(间断)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (286, N'USAGE', N'UZ', N'治疗', N'(会阴部)', N'(会阴部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (287, N'USAGE', N'UZ', N'治疗', N'会阴冲洗', N'会阴冲洗', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (288, N'USAGE', N'UZ', N'治疗', N'肛用', N'肛用', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (289, N'USAGE', N'UZ', N'治疗', N'塞阴道', N'塞阴道', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (290, N'USAGE', N'UZ', N'治疗', N'洗尿道口', N'洗尿道口', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (291, N'USAGE', N'UZ', N'治疗', N'(自执行)', N'(自执行)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (292, N'USAGE', N'UZ', N'治疗', N'(面部)', N'(面部)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (295, N'USAGE', N'UZ', N'治疗', N'(创面用)', N'(创面用)', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (296, N'USAGE', N'UZ', N'治疗', N'腹膜透析*', N'腹膜透析*', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (297, N'USAGE', N'UZ', N'治疗', N'术前滴眼', N'术前滴眼', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (298, N'USAGE', N'UZ', N'治疗', N'肿块内注入', N'肿块内注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (299, N'USAGE', N'UZ', N'治疗', N'局麻', N'局麻', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (300, N'USAGE', N'UZ', N'治疗', N'涂口腔患处', N'涂口腔患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (301, N'USAGE', N'UZ', N'治疗', N'涂面部患处', N'涂面部患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (302, N'USAGE', N'UZ', N'治疗', N'涂头皮患处', N'涂头皮患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (303, N'USAGE', N'UZ', N'治疗', N'涂胸部患处', N'涂胸部患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (304, N'USAGE', N'UZ', N'治疗', N'涂背部患处', N'涂背部患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (305, N'USAGE', N'UZ', N'治疗', N'涂躯干患处', N'涂躯干患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (306, N'USAGE', N'UZ', N'治疗', N'涂左上肢患处', N'涂左上肢患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (307, N'USAGE', N'UZ', N'治疗', N'涂右上肢患处', N'涂右上肢患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (308, N'USAGE', N'UZ', N'治疗', N'涂双上肢患处', N'涂双上肢患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (309, N'USAGE', N'UZ', N'治疗', N'涂会阴患处', N'涂会阴患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (310, N'USAGE', N'UZ', N'治疗', N'涂臀部患处', N'涂臀部患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (311, N'USAGE', N'UZ', N'治疗', N'涂左下肢患处', N'涂左下肢患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (312, N'USAGE', N'UZ', N'治疗', N'涂右下肢患处', N'涂右下肢患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (313, N'USAGE', N'UZ', N'治疗', N'涂双下肢患处', N'涂双下肢患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (314, N'USAGE', N'UZ', N'治疗', N'涂左手患处', N'涂左手患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (315, N'USAGE', N'UZ', N'治疗', N'涂右手患处', N'涂右手患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (316, N'USAGE', N'UZ', N'治疗', N'涂双手患处', N'涂双手患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (317, N'USAGE', N'UZ', N'治疗', N'涂左足患处', N'涂左足患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (318, N'USAGE', N'UZ', N'治疗', N'涂右足患处', N'涂右足患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (319, N'USAGE', N'UZ', N'治疗', N'涂双足患处', N'涂双足患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (320, N'USAGE', N'UZ', N'治疗', N'涂甲患处', N'涂甲患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (321, N'USAGE', N'UZ', N'治疗', N'涂左耳患处', N'涂左耳患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (322, N'USAGE', N'UZ', N'治疗', N'涂右耳患处', N'涂右耳患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (323, N'USAGE', N'UZ', N'治疗', N'涂双耳患处', N'涂双耳患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (324, N'USAGE', N'UZ', N'治疗', N'涂鼻患处', N'涂鼻患处', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (325, N'USAGE', N'UZ', N'治疗', N'喷雾吸入', N'喷雾吸入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (326, N'USAGE', N'UZ', N'治疗', N'胃管注入*', N'胃管注入*', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (327, N'USAGE', N'UZ', N'治疗', N'鼓室内注药', N'鼓室内注药', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (328, N'USAGE', N'UZ', N'治疗', N'吸痰用', N'吸痰用', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (329, N'USAGE', N'UZ', N'治疗', N'外用', N'外用', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (330, N'USAGE', N'UZ', N'治疗', N'封管用', N'封管用', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (331, N'USAGE', N'UZ', N'治疗', N'鼻肠管内', N'鼻肠管内', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (332, N'USAGE', N'UZ', N'治疗', N'测CVP用', N'测CVP用', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (333, N'USAGE', N'UZ', N'治疗', N'滴骨牵引', N'滴骨牵引', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (334, N'USAGE', N'UZ', N'治疗', N'呼吸机湿化用', N'呼吸机湿化用', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (335, N'USAGE', N'UZ', N'治疗', N'取药', N'取药', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (336, N'USAGE', N'UZ', N'治疗', N'小肠管内注入', N'小肠管内注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (337, N'USAGE', N'UZ', N'治疗', N'小肠管注入', N'小肠管注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (338, N'USAGE', N'UZ', N'治疗', N'小肠营养管内注入', N'小肠营养管内注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (339, N'USAGE', N'UZ', N'治疗', N'鼻肠管注入*', N'鼻肠管注入*', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (340, N'USAGE', N'UZ', N'治疗', N'鼻肠管注入', N'鼻肠管注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (341, N'USAGE', N'UZ', N'治疗', N'小肠管注入*', N'小肠管注入*', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (342, N'USAGE', N'UZ', N'治疗', N'小肠营养管注入*', N'小肠营养管注入*', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (343, N'USAGE', N'UZ', N'治疗', N'小肠营养管内泵注', N'小肠营养管内泵注', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (344, N'USAGE', N'UZ', N'治疗', N'小肠营养官内', N'小肠营养官内', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (345, N'USAGE', N'UZ', N'治疗', N'小肠营养管内', N'小肠营养管内', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (346, N'USAGE', N'UZ', N'治疗', N'小肠营养管注入', N'小肠营养管注入', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (347, N'USAGE', N'UZ', N'治疗', N'faa', N'faa', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (348, N'USAGE', N'UZ', N'治疗', N'透析用', N'透析用', N'1', 600, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (353, N'USAGE', N'INJECT', N'注射', N'IM,术前30''', N'IM,术前30''', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (354, N'USAGE', N'INJECT', N'注射', N'IM,术前30''', N'IM,术前30''', N'1', 900, NULL)
INSERT [dbo].[COM_DIC] ([ID], [DIC_TYPE], [CODE], [NAME], [HIS_CODE], [HIS_NAME], [FLAG], [SORT_NO], [LIQUOR]) VALUES (355, N'CHARGE', N'2', N'公费', N'市 公 医', N'市 公 医', N'1', 0, NULL)
SET IDENTITY_INSERT [dbo].[COM_DIC] OFF
